ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:32717").setExtent([654629.973048, 9233623.516943, 658017.694200, 9235808.529060]);
var wms_layers = [];


        var lyr_GoogleRoad_0 = new ol.layer.Tile({
            'title': 'Google Road',
            'opacity': 0.400000,
            
            
            source: new ol.source.XYZ({
            attributions: ' &nbsp &middot; <a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>',
                url: 'https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}'
            })
        });
var format_Reservorio_1 = new ol.format.GeoJSON();
var features_Reservorio_1 = format_Reservorio_1.readFeatures(json_Reservorio_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Reservorio_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Reservorio_1.addFeatures(features_Reservorio_1);
var lyr_Reservorio_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Reservorio_1, 
                style: style_Reservorio_1,
                popuplayertitle: 'Reservorio',
                interactive: false,
                title: '<img src="styles/legend/Reservorio_1.png" /> Reservorio'
            });
var format_ZaaElevaciones_2 = new ol.format.GeoJSON();
var features_ZaaElevaciones_2 = format_ZaaElevaciones_2.readFeatures(json_ZaaElevaciones_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_ZaaElevaciones_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ZaaElevaciones_2.addFeatures(features_ZaaElevaciones_2);
var lyr_ZaaElevaciones_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ZaaElevaciones_2, 
                style: style_ZaaElevaciones_2,
                popuplayertitle: 'Zaña-Elevaciones',
                interactive: false,
    title: 'Zaña-Elevaciones<br />\
    <img src="styles/legend/ZaaElevaciones_2_0.png" /> 51 - 54<br />\
    <img src="styles/legend/ZaaElevaciones_2_1.png" /> 54 - 64.5<br />\
    <img src="styles/legend/ZaaElevaciones_2_2.png" /> 64.5 - 106.5<br />' });
var format_Tuberia_Secundaria_3 = new ol.format.GeoJSON();
var features_Tuberia_Secundaria_3 = format_Tuberia_Secundaria_3.readFeatures(json_Tuberia_Secundaria_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Tuberia_Secundaria_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tuberia_Secundaria_3.addFeatures(features_Tuberia_Secundaria_3);
var lyr_Tuberia_Secundaria_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tuberia_Secundaria_3, 
                style: style_Tuberia_Secundaria_3,
                popuplayertitle: 'Tuberia_Secundaria',
                interactive: true,
    title: 'Tuberia_Secundaria<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_0.png" /> Desconocido<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_1.png" /> 50<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_2.png" /> 75<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_3.png" /> 90<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_4.png" /> 110<br />\
    <img src="styles/legend/Tuberia_Secundaria_3_5.png" /> 160<br />' });
var format_Tuberia_Primaria_4 = new ol.format.GeoJSON();
var features_Tuberia_Primaria_4 = format_Tuberia_Primaria_4.readFeatures(json_Tuberia_Primaria_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Tuberia_Primaria_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tuberia_Primaria_4.addFeatures(features_Tuberia_Primaria_4);
var lyr_Tuberia_Primaria_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tuberia_Primaria_4, 
                style: style_Tuberia_Primaria_4,
                popuplayertitle: 'Tuberia_Primaria',
                interactive: true,
    title: 'Tuberia_Primaria<br />\
    <img src="styles/legend/Tuberia_Primaria_4_0.png" /> Desconocido<br />\
    <img src="styles/legend/Tuberia_Primaria_4_1.png" /> 200<br />\
    <img src="styles/legend/Tuberia_Primaria_4_2.png" /> <br />' });
var format_Pozo_de_produccion_5 = new ol.format.GeoJSON();
var features_Pozo_de_produccion_5 = format_Pozo_de_produccion_5.readFeatures(json_Pozo_de_produccion_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Pozo_de_produccion_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Pozo_de_produccion_5.addFeatures(features_Pozo_de_produccion_5);
var lyr_Pozo_de_produccion_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Pozo_de_produccion_5, 
                style: style_Pozo_de_produccion_5,
                popuplayertitle: 'Pozo_de_produccion',
                interactive: false,
                title: '<img src="styles/legend/Pozo_de_produccion_5.png" /> Pozo_de_produccion'
            });
var format_Hidrantes_6 = new ol.format.GeoJSON();
var features_Hidrantes_6 = format_Hidrantes_6.readFeatures(json_Hidrantes_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Hidrantes_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Hidrantes_6.addFeatures(features_Hidrantes_6);
var lyr_Hidrantes_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Hidrantes_6, 
                style: style_Hidrantes_6,
                popuplayertitle: 'Hidrantes',
                interactive: false,
                title: '<img src="styles/legend/Hidrantes_6.png" /> Hidrantes'
            });
var format_Valvulas_de_control_7 = new ol.format.GeoJSON();
var features_Valvulas_de_control_7 = format_Valvulas_de_control_7.readFeatures(json_Valvulas_de_control_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32717'});
var jsonSource_Valvulas_de_control_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Valvulas_de_control_7.addFeatures(features_Valvulas_de_control_7);
var lyr_Valvulas_de_control_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Valvulas_de_control_7, 
                style: style_Valvulas_de_control_7,
                popuplayertitle: 'Valvulas_de_control',
                interactive: false,
                title: '<img src="styles/legend/Valvulas_de_control_7.png" /> Valvulas_de_control'
            });
var group_SistAguaZaa = new ol.layer.Group({
                                layers: [lyr_Reservorio_1,lyr_ZaaElevaciones_2,lyr_Tuberia_Secundaria_3,lyr_Tuberia_Primaria_4,lyr_Pozo_de_produccion_5,lyr_Hidrantes_6,lyr_Valvulas_de_control_7,],
                                fold: 'open',
                                title: 'SistAguaZaña'});

lyr_GoogleRoad_0.setVisible(true);lyr_Reservorio_1.setVisible(true);lyr_ZaaElevaciones_2.setVisible(true);lyr_Tuberia_Secundaria_3.setVisible(true);lyr_Tuberia_Primaria_4.setVisible(true);lyr_Pozo_de_produccion_5.setVisible(true);lyr_Hidrantes_6.setVisible(true);lyr_Valvulas_de_control_7.setVisible(true);
var layersList = [lyr_GoogleRoad_0,group_SistAguaZaa];
lyr_Reservorio_1.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'NAME': 'Nombre', 'OLDCODE': 'Código antiguo', 'TANKTYPE': 'Tipo de reservorio', 'PRIMARYNETWORK': 'Primario', 'HOLDERTYPE': 'Tipo de apoyo', 'TANKFUNCTION': 'Tipo de funcionamiento', 'OPDATE': 'Fecha puesta en marcha', 'PERIMETERFENCE': 'Cerco perimetral', 'STATUS': 'Estado', 'VOLUME': 'Volumen', 'OPERATORNAME': 'Nombre del operario', 'TELEPHONE': 'Teléfono', 'DEALERCOMP': 'Empresa concesionaria', 'SUPPLYCODE': 'Código de suministro', 'CHARGE': 'Carga', 'RATE': 'Tarifa', 'TERRAINLEVEL': 'Cota de terreno', 'INVERT': 'Cota mínima de fondo', 'WATERLEVEL': 'Cota de nivel de agua', 'LOCDESC': 'Descripción localización', 'GPSDATE': 'Fecha de GPS', 'ROTATION': 'Rotación', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'LASTREVDATE': 'Fecha última revisión', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'EXPEDIENTCODE': 'Código de expediente', 'SCADACODE': 'Código SCADA', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'ANCILLARYROLE': 'ANCILLARYROLE', 'COVERLEVEL': 'Cota de tapa', 'CONDITION': 'Condición de conservación', 'NEWCODE': 'Código nuevo', 'PENT': 'PENT', 'PSMIN': 'PSMIN', 'PSMAX': 'PSMAX', });
lyr_ZaaElevaciones_2.set('fieldAliases', {'fid': 'fid', 'FACILITYID': 'FACILITYID', 'CONTOURTYP': 'CONTOURTYP', 'ELEVATION': 'ELEVATION', 'DATUMV': 'DATUMV', 'REALLENGTH': 'REALLENGTH', 'OWNEDBY': 'OWNEDBY', 'MAINTBY': 'MAINTBY', 'LASTUPDATE': 'LASTUPDATE', 'LASTEDITOR': 'LASTEDITOR', 'LASTREVDAT': 'LASTREVDAT', 'LASTCAPDAT': 'LASTCAPDAT', 'SURVEYDATE': 'SURVEYDATE', 'SURVEYOR': 'SURVEYOR', 'EXPEDIENTC': 'EXPEDIENTC', 'DISTRICT': 'DISTRICT', });
lyr_Tuberia_Secundaria_3.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'DIAMETER': 'Diámetro', 'MATERIAL': 'MATERIAL', 'SOURCE': 'Fuente', 'RUGOSITY': 'Rugosidad', 'RESIDUALCHLORINE': 'Cloro residual', 'TERRAINTYPE': 'Tipo de terreno', 'EXPOSED': 'Expuesto', 'THEORICCLASS': 'Clase teórica', 'REALCLASS': 'Clase real', 'PRIMARYNETWORK': 'Primario', 'NETWORKTYPE': 'Tipo de red', 'WATERTYPE': 'Tipo de agua', 'MATRIX': 'Matriz', 'REALLENGTH': 'Longitud real', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'LASTREVDATE': 'Fecha última revisión', 'CONDITION': 'Condición de conservación', 'DETECTIONWO': 'Actuaciones de detección', 'LASTREPAIRDATE': 'Fecha de última reparación', 'REPAIRS': 'Reparaciones', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'ESTIMATEDRETIREDDATE': 'Fecha de retiro estimada', 'EXPEDIENTCODE': 'Código de expediente', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'CHANGEREASON': 'Motivo de Cambio', 'CHANGEDOCUMENT': 'Documento Sustento', 'INSTALLATIONDEPTH': 'Profundidad de instalación', 'NAME': 'Nombre Tubería', 'NETWORKLOCATION': 'Ubicado en', 'SHAPE_Length': 'SHAPE_Length', });
lyr_Tuberia_Primaria_4.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'DIAMETER': 'Diámetro', 'MATERIAL': 'MATERIAL', 'SOURCE': 'Fuente', 'RUGOSITY': 'Rugosidad', 'RESIDUALCHLORINE': 'Cloro residual', 'TERRAINTYPE': 'Tipo de terreno', 'EXPOSED': 'Expuesto', 'THEORICCLASS': 'Clase teórica', 'REALCLASS': 'Clase real', 'PRIMARYNETWORK': 'Primario', 'NETWORKTYPE': 'Tipo de red', 'WATERTYPE': 'Tipo de agua', 'MATRIX': 'Matriz', 'REALLENGTH': 'Longitud real', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'LASTREVDATE': 'Fecha última revisión', 'CONDITION': 'Condición de conservación', 'DETECTIONWO': 'Actuaciones de detección', 'LASTREPAIRDATE': 'Fecha de última reparación', 'REPAIRS': 'Reparaciones', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'ESTIMATEDRETIREDDATE': 'Fecha de retiro estimada', 'EXPEDIENTCODE': 'Código de expediente', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'CHANGEREASON': 'Motivo de Cambio', 'CHANGEDOCUMENT': 'Documento Sustento', 'INSTALLATIONDEPTH': 'Profundidad de instalación', 'NAME': 'Nombre Tubería', 'NETWORKLOCATION': 'Ubicado en', 'SHAPE_Length': 'SHAPE_Length', });
lyr_Pozo_de_produccion_5.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'NAME': 'Nombre', 'OLDCODE': 'Código antiguo', 'WELLUSE': 'Uso del pozo', 'OPDATE': 'Fecha puesta en marcha', 'PERIMETERFENCE': 'Cerco perimetral', 'STATUS': 'Estado', 'MEASUREDATE': 'Fecha de medición', 'STATICINITIALLEVEL': 'Nivel estático inicial', 'DINAMICLEVEL': 'Nivel dinámico', 'EFICIENCY': 'Eficiencia', 'LASTSTATICLEVEL': 'Último nivel estático', 'MEASUREFRECUENCY': 'Frecuencia de medida', 'WELLEQUIPMENT': 'Equipamiento del pozo', 'WELLOBJECTIVE': 'Objetivo del pozo', 'DRILLCOMPANY': 'Compañía perforadora', 'GEOMORPHOLOGY': 'Geomorfología', 'RATEDFLOW': 'Caudal nominal', 'EXPLOITABLEFLOW': 'Caudal explotable', 'BLINDPIPEDIAMETER': 'Diámetro de tubería ciega', 'BLINDPIPELARGO': 'Longitud de tubería ciega ', 'BLINDPIPENUMBER': 'Cantidad de tubería ciega', 'FILTERDIAMETER': 'Diámetro de filtros', 'FILTERLARGO': 'Longitud de filtros', 'FILTERTYPE': 'Tipo de filtros', 'FILTERNUMBER': 'Número de filtros', 'DEALERCOMP': 'Empresa concesionaria', 'SUPPLYCODE': 'Código de suministro', 'CHARGE': 'Carga', 'RATE': 'Tarifa', 'TERRAINLEVEL': 'Cota de terreno', 'TOTALDEPTH': 'Profundidad total', 'TUBEDDEPTH': 'Profundidad entubada', 'LOCDESC': 'Descripción localización', 'GPSDATE': 'Fecha de GPS', 'ROTATION': 'Rotación', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'CONDITION': 'Condición de conservación', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'EXPEDIENTCODE': 'Código de expediente', 'SCADACODE': 'Código SCADA', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'ANCILLARYROLE': 'ANCILLARYROLE', 'STATICLEVEL': 'Nivel Estático', 'REFERENCEPOINT': 'Punto de Referencia', 'X': 'X', 'Y': 'Y', 'SAMPLINGDATE': 'Fecha de muestreo', 'PH': 'PH', 'CONDUCTIVITY': 'Conductividad eléctrica', 'SULFATES': 'Sulfatos', 'NITRATES': 'Nitratos', 'CHLORIDES': 'Cloruros', 'HARDNESS': 'Dureza', 'BLINDPIPELONG': 'BLINDPIPELONG', 'FILTERLONG': 'FILTERLONG', 'LASTDINAMICLEVEL': 'LASTDINAMICLEVEL', });
lyr_Hidrantes_6.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'HYDRANTTYPE': 'Tipo de hidrante', 'DIAMETER': 'Diametro', 'MANUFACTURER': 'Fabricante', 'MODEL': 'Modelo', 'OPERABLE': 'Operativo', 'FLOW': 'Caudal', 'NIS': 'NIS', 'SUPPLYTIME': 'Horario de Abastecimiento', 'SUPPLYID': 'Código de Abastecimiento', 'LASTSERVICE': 'Fecha último servicio', 'OBSERVATIONS': 'Observaciones', 'DEPTH': 'Profundidad', 'LOCDESC': 'Descripción localización', 'GPSDATE': 'Fecha de GPS', 'PLACEMENT': 'PLACEMENT', 'ROTATION': 'Rotación', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'LASTREVDATE': 'Fecha última revisión', 'LASTREPAIRDATE': 'Fecha de última reparación', 'REPAIRS': 'Reparaciones', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'EXPEDIENTCODE': 'Código de expediente', 'SCADACODE': 'Código SCADA', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'X': 'X', 'Y': 'Y', 'Z': 'Z', 'GPSEDITOR': 'Editor GPS', 'CHANGEREASON': 'Motivo de Cambio', 'CHANGEDOCUMENT': 'Documento Sustento', 'NUMBOCAMAZAS': 'Número de Bocamazas', });
lyr_Valvulas_de_control_7.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'FACILITYID': 'Identificador', 'VALVETYPE': 'Tipo de válvula', 'VALVEFUNCTION': 'Función de válvula', 'VALVEDRIVE': 'Accionamiento', 'DIAMETER': 'Diámetro', 'MATERIAL': 'MATERIAL', 'MANUFACTURER': 'Fabricante', 'MODEL': 'Modelo', 'NOMPRESSURE': 'Presión nominal', 'CONNECTIONTYPE': 'Conexión', 'DEPTH': 'Profundidad', 'LOCDESC': 'Descripción localización', 'GPSDATE': 'Fecha de GPS', 'ROTATION': 'Rotación', 'ENABLED': 'Habilitado', 'ACTIVEFLAG': 'Activo', 'OWNEDBY': 'Propiedad de', 'MAINTBY': 'Administrado por', 'LASTUPDATE': 'Última actualización', 'LASTEDITOR': 'Último editor', 'LASTREVDATE': 'Fecha última revisión', 'LASTREPAIRDATE': 'Fecha de última reparación', 'REPAIRS': 'Reparaciones', 'INSTALLDATE': 'Fecha de instalación', 'INSTALLER': 'Instalador', 'EXPEDIENTCODE': 'Código de expediente', 'SCADACODE': 'Código SCADA', 'SAPCODE': 'Código SAP', 'DISTRICT': 'Municipalidad', 'CENTERCOST': 'Centro de costo', 'X': 'X', 'Y': 'Y', 'Z': 'Z', 'GPSEDITOR': 'Editor GPS', 'CHANGEREASON': 'Motivo de Cambio', 'CHANGEDOCUMENT': 'Documento Sustento', 'vinculacion': 'vinculacion', });
lyr_Reservorio_1.set('fieldImages', {'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'NAME': 'TextEdit', 'OLDCODE': 'TextEdit', 'TANKTYPE': 'ValueMap', 'PRIMARYNETWORK': 'ValueMap', 'HOLDERTYPE': 'ValueMap', 'TANKFUNCTION': 'ValueMap', 'OPDATE': 'DateTime', 'PERIMETERFENCE': 'ValueMap', 'STATUS': 'ValueMap', 'VOLUME': 'TextEdit', 'OPERATORNAME': 'TextEdit', 'TELEPHONE': 'TextEdit', 'DEALERCOMP': 'TextEdit', 'SUPPLYCODE': 'TextEdit', 'CHARGE': 'TextEdit', 'RATE': 'TextEdit', 'TERRAINLEVEL': 'TextEdit', 'INVERT': 'TextEdit', 'WATERLEVEL': 'TextEdit', 'LOCDESC': 'TextEdit', 'GPSDATE': 'DateTime', 'ROTATION': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDATE': 'DateTime', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'EXPEDIENTCODE': 'TextEdit', 'SCADACODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'ANCILLARYROLE': 'ValueMap', 'COVERLEVEL': 'TextEdit', 'CONDITION': 'ValueMap', 'NEWCODE': 'TextEdit', 'PENT': 'TextEdit', 'PSMIN': 'TextEdit', 'PSMAX': 'TextEdit', });
lyr_ZaaElevaciones_2.set('fieldImages', {'fid': '', 'FACILITYID': 'TextEdit', 'CONTOURTYP': 'TextEdit', 'ELEVATION': 'TextEdit', 'DATUMV': 'TextEdit', 'REALLENGTH': 'TextEdit', 'OWNEDBY': 'TextEdit', 'MAINTBY': 'TextEdit', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDAT': 'DateTime', 'LASTCAPDAT': 'DateTime', 'SURVEYDATE': 'DateTime', 'SURVEYOR': 'TextEdit', 'EXPEDIENTC': 'TextEdit', 'DISTRICT': 'TextEdit', });
lyr_Tuberia_Secundaria_3.set('fieldImages', {'fid': '', 'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'DIAMETER': 'ValueMap', 'MATERIAL': 'ValueMap', 'SOURCE': 'TextEdit', 'RUGOSITY': 'TextEdit', 'RESIDUALCHLORINE': 'TextEdit', 'TERRAINTYPE': 'ValueMap', 'EXPOSED': 'ValueMap', 'THEORICCLASS': 'TextEdit', 'REALCLASS': 'TextEdit', 'PRIMARYNETWORK': 'ValueMap', 'NETWORKTYPE': 'ValueMap', 'WATERTYPE': 'ValueMap', 'MATRIX': 'TextEdit', 'REALLENGTH': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDATE': 'DateTime', 'CONDITION': 'ValueMap', 'DETECTIONWO': 'Range', 'LASTREPAIRDATE': 'DateTime', 'REPAIRS': 'TextEdit', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'ESTIMATEDRETIREDDATE': 'DateTime', 'EXPEDIENTCODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'CHANGEREASON': 'ValueMap', 'CHANGEDOCUMENT': 'TextEdit', 'INSTALLATIONDEPTH': 'TextEdit', 'NAME': 'TextEdit', 'NETWORKLOCATION': 'ValueMap', 'SHAPE_Length': 'TextEdit', });
lyr_Tuberia_Primaria_4.set('fieldImages', {'fid': '', 'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'DIAMETER': 'ValueMap', 'MATERIAL': 'ValueMap', 'SOURCE': 'TextEdit', 'RUGOSITY': 'TextEdit', 'RESIDUALCHLORINE': 'TextEdit', 'TERRAINTYPE': 'ValueMap', 'EXPOSED': 'ValueMap', 'THEORICCLASS': 'TextEdit', 'REALCLASS': 'TextEdit', 'PRIMARYNETWORK': 'ValueMap', 'NETWORKTYPE': 'ValueMap', 'WATERTYPE': 'ValueMap', 'MATRIX': 'TextEdit', 'REALLENGTH': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDATE': 'DateTime', 'CONDITION': 'ValueMap', 'DETECTIONWO': 'Range', 'LASTREPAIRDATE': 'DateTime', 'REPAIRS': 'TextEdit', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'ESTIMATEDRETIREDDATE': 'DateTime', 'EXPEDIENTCODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'CHANGEREASON': 'ValueMap', 'CHANGEDOCUMENT': 'TextEdit', 'INSTALLATIONDEPTH': 'TextEdit', 'NAME': 'TextEdit', 'NETWORKLOCATION': 'ValueMap', 'SHAPE_Length': 'TextEdit', });
lyr_Pozo_de_produccion_5.set('fieldImages', {'fid': 'TextEdit', 'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'NAME': 'TextEdit', 'OLDCODE': 'TextEdit', 'WELLUSE': 'ValueMap', 'OPDATE': 'DateTime', 'PERIMETERFENCE': 'ValueMap', 'STATUS': 'ValueMap', 'MEASUREDATE': 'DateTime', 'STATICINITIALLEVEL': 'TextEdit', 'DINAMICLEVEL': 'TextEdit', 'EFICIENCY': 'TextEdit', 'LASTSTATICLEVEL': 'TextEdit', 'MEASUREFRECUENCY': 'ValueMap', 'WELLEQUIPMENT': 'ValueMap', 'WELLOBJECTIVE': 'ValueMap', 'DRILLCOMPANY': 'ValueMap', 'GEOMORPHOLOGY': 'ValueMap', 'RATEDFLOW': 'TextEdit', 'EXPLOITABLEFLOW': 'TextEdit', 'BLINDPIPEDIAMETER': 'ValueMap', 'BLINDPIPELARGO': 'TextEdit', 'BLINDPIPENUMBER': 'TextEdit', 'FILTERDIAMETER': 'ValueMap', 'FILTERLARGO': 'TextEdit', 'FILTERTYPE': 'ValueMap', 'FILTERNUMBER': 'TextEdit', 'DEALERCOMP': 'TextEdit', 'SUPPLYCODE': 'TextEdit', 'CHARGE': 'TextEdit', 'RATE': 'TextEdit', 'TERRAINLEVEL': 'TextEdit', 'TOTALDEPTH': 'TextEdit', 'TUBEDDEPTH': 'TextEdit', 'LOCDESC': 'TextEdit', 'GPSDATE': 'DateTime', 'ROTATION': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'CONDITION': 'ValueMap', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'EXPEDIENTCODE': 'TextEdit', 'SCADACODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'ANCILLARYROLE': 'ValueMap', 'STATICLEVEL': 'TextEdit', 'REFERENCEPOINT': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'SAMPLINGDATE': 'DateTime', 'PH': 'TextEdit', 'CONDUCTIVITY': 'TextEdit', 'SULFATES': 'TextEdit', 'NITRATES': 'TextEdit', 'CHLORIDES': 'TextEdit', 'HARDNESS': 'TextEdit', 'BLINDPIPELONG': 'ValueMap', 'FILTERLONG': 'TextEdit', 'LASTDINAMICLEVEL': 'TextEdit', });
lyr_Hidrantes_6.set('fieldImages', {'fid': 'TextEdit', 'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'HYDRANTTYPE': 'ValueMap', 'DIAMETER': 'ValueMap', 'MANUFACTURER': 'ValueMap', 'MODEL': 'TextEdit', 'OPERABLE': 'ValueMap', 'FLOW': 'TextEdit', 'NIS': 'TextEdit', 'SUPPLYTIME': 'Range', 'SUPPLYID': 'TextEdit', 'LASTSERVICE': 'DateTime', 'OBSERVATIONS': 'TextEdit', 'DEPTH': 'TextEdit', 'LOCDESC': 'TextEdit', 'GPSDATE': 'DateTime', 'PLACEMENT': 'ValueMap', 'ROTATION': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDATE': 'DateTime', 'LASTREPAIRDATE': 'DateTime', 'REPAIRS': 'Range', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'EXPEDIENTCODE': 'TextEdit', 'SCADACODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'Z': 'TextEdit', 'GPSEDITOR': 'TextEdit', 'CHANGEREASON': 'TextEdit', 'CHANGEDOCUMENT': 'TextEdit', 'NUMBOCAMAZAS': 'Range', });
lyr_Valvulas_de_control_7.set('fieldImages', {'fid': 'TextEdit', 'OBJECTID': 'TextEdit', 'FACILITYID': 'TextEdit', 'VALVETYPE': 'ValueMap', 'VALVEFUNCTION': 'ValueMap', 'VALVEDRIVE': 'ValueMap', 'DIAMETER': 'ValueMap', 'MATERIAL': 'ValueMap', 'MANUFACTURER': 'ValueMap', 'MODEL': 'TextEdit', 'NOMPRESSURE': 'TextEdit', 'CONNECTIONTYPE': 'ValueMap', 'DEPTH': 'TextEdit', 'LOCDESC': 'TextEdit', 'GPSDATE': 'DateTime', 'ROTATION': 'TextEdit', 'ENABLED': 'ValueMap', 'ACTIVEFLAG': 'ValueMap', 'OWNEDBY': 'ValueMap', 'MAINTBY': 'ValueMap', 'LASTUPDATE': 'DateTime', 'LASTEDITOR': 'TextEdit', 'LASTREVDATE': 'DateTime', 'LASTREPAIRDATE': 'DateTime', 'REPAIRS': 'TextEdit', 'INSTALLDATE': 'DateTime', 'INSTALLER': 'ValueMap', 'EXPEDIENTCODE': 'TextEdit', 'SCADACODE': 'TextEdit', 'SAPCODE': 'TextEdit', 'DISTRICT': 'ValueMap', 'CENTERCOST': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'Z': 'TextEdit', 'GPSEDITOR': 'TextEdit', 'CHANGEREASON': 'ValueMap', 'CHANGEDOCUMENT': 'TextEdit', 'vinculacion': 'TextEdit', });
lyr_Reservorio_1.set('fieldLabels', {'OBJECTID': 'no label', 'FACILITYID': 'no label', 'NAME': 'no label', 'OLDCODE': 'no label', 'TANKTYPE': 'no label', 'PRIMARYNETWORK': 'no label', 'HOLDERTYPE': 'no label', 'TANKFUNCTION': 'no label', 'OPDATE': 'no label', 'PERIMETERFENCE': 'no label', 'STATUS': 'no label', 'VOLUME': 'no label', 'OPERATORNAME': 'no label', 'TELEPHONE': 'no label', 'DEALERCOMP': 'no label', 'SUPPLYCODE': 'no label', 'CHARGE': 'no label', 'RATE': 'no label', 'TERRAINLEVEL': 'no label', 'INVERT': 'no label', 'WATERLEVEL': 'no label', 'LOCDESC': 'no label', 'GPSDATE': 'no label', 'ROTATION': 'no label', 'ENABLED': 'no label', 'ACTIVEFLAG': 'no label', 'OWNEDBY': 'no label', 'MAINTBY': 'no label', 'LASTUPDATE': 'no label', 'LASTEDITOR': 'no label', 'LASTREVDATE': 'no label', 'INSTALLDATE': 'no label', 'INSTALLER': 'no label', 'EXPEDIENTCODE': 'no label', 'SCADACODE': 'no label', 'SAPCODE': 'no label', 'DISTRICT': 'no label', 'CENTERCOST': 'no label', 'ANCILLARYROLE': 'no label', 'COVERLEVEL': 'no label', 'CONDITION': 'no label', 'NEWCODE': 'no label', 'PENT': 'no label', 'PSMIN': 'no label', 'PSMAX': 'no label', });
lyr_ZaaElevaciones_2.set('fieldLabels', {'fid': 'no label', 'FACILITYID': 'no label', 'CONTOURTYP': 'no label', 'ELEVATION': 'no label', 'DATUMV': 'no label', 'REALLENGTH': 'no label', 'OWNEDBY': 'no label', 'MAINTBY': 'no label', 'LASTUPDATE': 'no label', 'LASTEDITOR': 'no label', 'LASTREVDAT': 'no label', 'LASTCAPDAT': 'no label', 'SURVEYDATE': 'no label', 'SURVEYOR': 'no label', 'EXPEDIENTC': 'no label', 'DISTRICT': 'no label', });
lyr_Tuberia_Secundaria_3.set('fieldLabels', {'fid': 'hidden field', 'OBJECTID': 'hidden field', 'FACILITYID': 'hidden field', 'DIAMETER': 'inline label - always visible', 'MATERIAL': 'hidden field', 'SOURCE': 'hidden field', 'RUGOSITY': 'hidden field', 'RESIDUALCHLORINE': 'hidden field', 'TERRAINTYPE': 'hidden field', 'EXPOSED': 'hidden field', 'THEORICCLASS': 'hidden field', 'REALCLASS': 'hidden field', 'PRIMARYNETWORK': 'hidden field', 'NETWORKTYPE': 'hidden field', 'WATERTYPE': 'hidden field', 'MATRIX': 'hidden field', 'REALLENGTH': 'hidden field', 'ENABLED': 'hidden field', 'ACTIVEFLAG': 'hidden field', 'OWNEDBY': 'hidden field', 'MAINTBY': 'hidden field', 'LASTUPDATE': 'hidden field', 'LASTEDITOR': 'hidden field', 'LASTREVDATE': 'hidden field', 'CONDITION': 'hidden field', 'DETECTIONWO': 'hidden field', 'LASTREPAIRDATE': 'hidden field', 'REPAIRS': 'hidden field', 'INSTALLDATE': 'hidden field', 'INSTALLER': 'hidden field', 'ESTIMATEDRETIREDDATE': 'hidden field', 'EXPEDIENTCODE': 'hidden field', 'SAPCODE': 'hidden field', 'DISTRICT': 'hidden field', 'CENTERCOST': 'hidden field', 'CHANGEREASON': 'hidden field', 'CHANGEDOCUMENT': 'hidden field', 'INSTALLATIONDEPTH': 'hidden field', 'NAME': 'hidden field', 'NETWORKLOCATION': 'hidden field', 'SHAPE_Length': 'hidden field', });
lyr_Tuberia_Primaria_4.set('fieldLabels', {'fid': 'hidden field', 'OBJECTID': 'hidden field', 'FACILITYID': 'hidden field', 'DIAMETER': 'inline label - always visible', 'MATERIAL': 'hidden field', 'SOURCE': 'hidden field', 'RUGOSITY': 'hidden field', 'RESIDUALCHLORINE': 'hidden field', 'TERRAINTYPE': 'hidden field', 'EXPOSED': 'header label - always visible', 'THEORICCLASS': 'hidden field', 'REALCLASS': 'hidden field', 'PRIMARYNETWORK': 'hidden field', 'NETWORKTYPE': 'hidden field', 'WATERTYPE': 'hidden field', 'MATRIX': 'hidden field', 'REALLENGTH': 'hidden field', 'ENABLED': 'hidden field', 'ACTIVEFLAG': 'hidden field', 'OWNEDBY': 'hidden field', 'MAINTBY': 'hidden field', 'LASTUPDATE': 'hidden field', 'LASTEDITOR': 'hidden field', 'LASTREVDATE': 'hidden field', 'CONDITION': 'hidden field', 'DETECTIONWO': 'hidden field', 'LASTREPAIRDATE': 'hidden field', 'REPAIRS': 'hidden field', 'INSTALLDATE': 'hidden field', 'INSTALLER': 'hidden field', 'ESTIMATEDRETIREDDATE': 'hidden field', 'EXPEDIENTCODE': 'hidden field', 'SAPCODE': 'hidden field', 'DISTRICT': 'hidden field', 'CENTERCOST': 'hidden field', 'CHANGEREASON': 'hidden field', 'CHANGEDOCUMENT': 'hidden field', 'INSTALLATIONDEPTH': 'hidden field', 'NAME': 'hidden field', 'NETWORKLOCATION': 'hidden field', 'SHAPE_Length': 'hidden field', });
lyr_Pozo_de_produccion_5.set('fieldLabels', {'fid': 'no label', 'OBJECTID': 'no label', 'FACILITYID': 'no label', 'NAME': 'no label', 'OLDCODE': 'no label', 'WELLUSE': 'no label', 'OPDATE': 'no label', 'PERIMETERFENCE': 'no label', 'STATUS': 'no label', 'MEASUREDATE': 'no label', 'STATICINITIALLEVEL': 'no label', 'DINAMICLEVEL': 'no label', 'EFICIENCY': 'no label', 'LASTSTATICLEVEL': 'no label', 'MEASUREFRECUENCY': 'no label', 'WELLEQUIPMENT': 'no label', 'WELLOBJECTIVE': 'no label', 'DRILLCOMPANY': 'no label', 'GEOMORPHOLOGY': 'no label', 'RATEDFLOW': 'no label', 'EXPLOITABLEFLOW': 'no label', 'BLINDPIPEDIAMETER': 'no label', 'BLINDPIPELARGO': 'no label', 'BLINDPIPENUMBER': 'no label', 'FILTERDIAMETER': 'no label', 'FILTERLARGO': 'no label', 'FILTERTYPE': 'no label', 'FILTERNUMBER': 'no label', 'DEALERCOMP': 'no label', 'SUPPLYCODE': 'no label', 'CHARGE': 'no label', 'RATE': 'no label', 'TERRAINLEVEL': 'no label', 'TOTALDEPTH': 'no label', 'TUBEDDEPTH': 'no label', 'LOCDESC': 'no label', 'GPSDATE': 'no label', 'ROTATION': 'no label', 'ENABLED': 'no label', 'ACTIVEFLAG': 'no label', 'OWNEDBY': 'no label', 'MAINTBY': 'no label', 'LASTUPDATE': 'no label', 'LASTEDITOR': 'no label', 'CONDITION': 'no label', 'INSTALLDATE': 'no label', 'INSTALLER': 'no label', 'EXPEDIENTCODE': 'no label', 'SCADACODE': 'no label', 'SAPCODE': 'no label', 'DISTRICT': 'no label', 'CENTERCOST': 'no label', 'ANCILLARYROLE': 'no label', 'STATICLEVEL': 'no label', 'REFERENCEPOINT': 'no label', 'X': 'no label', 'Y': 'no label', 'SAMPLINGDATE': 'no label', 'PH': 'no label', 'CONDUCTIVITY': 'no label', 'SULFATES': 'no label', 'NITRATES': 'no label', 'CHLORIDES': 'no label', 'HARDNESS': 'no label', 'BLINDPIPELONG': 'no label', 'FILTERLONG': 'no label', 'LASTDINAMICLEVEL': 'no label', });
lyr_Hidrantes_6.set('fieldLabels', {'fid': 'no label', 'OBJECTID': 'no label', 'FACILITYID': 'no label', 'HYDRANTTYPE': 'no label', 'DIAMETER': 'no label', 'MANUFACTURER': 'no label', 'MODEL': 'no label', 'OPERABLE': 'no label', 'FLOW': 'no label', 'NIS': 'no label', 'SUPPLYTIME': 'no label', 'SUPPLYID': 'no label', 'LASTSERVICE': 'no label', 'OBSERVATIONS': 'no label', 'DEPTH': 'no label', 'LOCDESC': 'no label', 'GPSDATE': 'no label', 'PLACEMENT': 'no label', 'ROTATION': 'no label', 'ENABLED': 'no label', 'ACTIVEFLAG': 'no label', 'OWNEDBY': 'no label', 'MAINTBY': 'no label', 'LASTUPDATE': 'no label', 'LASTEDITOR': 'no label', 'LASTREVDATE': 'no label', 'LASTREPAIRDATE': 'no label', 'REPAIRS': 'no label', 'INSTALLDATE': 'no label', 'INSTALLER': 'no label', 'EXPEDIENTCODE': 'no label', 'SCADACODE': 'no label', 'SAPCODE': 'no label', 'DISTRICT': 'no label', 'CENTERCOST': 'no label', 'X': 'no label', 'Y': 'no label', 'Z': 'no label', 'GPSEDITOR': 'no label', 'CHANGEREASON': 'no label', 'CHANGEDOCUMENT': 'no label', 'NUMBOCAMAZAS': 'no label', });
lyr_Valvulas_de_control_7.set('fieldLabels', {'fid': 'no label', 'OBJECTID': 'no label', 'FACILITYID': 'no label', 'VALVETYPE': 'no label', 'VALVEFUNCTION': 'no label', 'VALVEDRIVE': 'no label', 'DIAMETER': 'no label', 'MATERIAL': 'no label', 'MANUFACTURER': 'no label', 'MODEL': 'no label', 'NOMPRESSURE': 'no label', 'CONNECTIONTYPE': 'no label', 'DEPTH': 'no label', 'LOCDESC': 'no label', 'GPSDATE': 'no label', 'ROTATION': 'no label', 'ENABLED': 'no label', 'ACTIVEFLAG': 'no label', 'OWNEDBY': 'no label', 'MAINTBY': 'no label', 'LASTUPDATE': 'no label', 'LASTEDITOR': 'no label', 'LASTREVDATE': 'no label', 'LASTREPAIRDATE': 'no label', 'REPAIRS': 'no label', 'INSTALLDATE': 'no label', 'INSTALLER': 'no label', 'EXPEDIENTCODE': 'no label', 'SCADACODE': 'no label', 'SAPCODE': 'no label', 'DISTRICT': 'no label', 'CENTERCOST': 'no label', 'X': 'no label', 'Y': 'no label', 'Z': 'no label', 'GPSEDITOR': 'no label', 'CHANGEREASON': 'no label', 'CHANGEDOCUMENT': 'no label', 'vinculacion': 'no label', });
lyr_Valvulas_de_control_7.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});